### ISSUE TITLE
on_attach issue

### ISSUE THREAD

**Issue by craigmac** [sharksforarms/sharksforarms.github.io#1]
Following your excellent guide, I was hung up on the last part getting the completion working.

I think the issue was the on_attach call was written:
on_attach({..})

when I think it should read:
on_attach{} (not wrapped in parens)

So mine reads:
```lua
local my_lsp_attach = function(client)
    require'completion'.on_attach(client)
    require'diagnostic'on_attach(client)
end
require'nvim_lsp'.vimls.setup{on_attach=my_lsp_attach}
```

And it works for me that way, but I'm no expert on lua/api yet, so I could be way off!

**Comment by sharksforarms** [comment]
Yes, parens are optional :)

Both should work though...

https://www.lua.org/pil/5.html
