### ISSUE TITLE
Suggestion: Add example rust-analyzer config to neovim + Rust post

### ISSUE THREAD

**Issue by jam1garner** [sharksforarms/sharksforarms.github.io#10]
maybe just something like...

```lua
    server = { -- rust-analyzer options
      on_attach = on_attach,
      settings = {
        ["rust-analyzer"] = {
          checkOnSave = {
              command = "clippy"
          },
        }
      }
    },
```

as this would demonstrate the expected structure as well as the idiosyncrasies like needing to do ` ["rust-analyzer"]` to account for the `-` in the name.

**Comment by sharksforarms** [comment]
Good suggestion, I remember not knowing the format too and ended up scouring GitHub and peoples dotfiles for clues... I'll add something soon 👀

**Comment by jam1garner** [comment]
> Good suggestion, I remember not knowing the format too and ended up scouring GitHub and peoples dotfiles for clues... I'll add something soon eyes

yep lol that was my experience, took me way longer than I'd like to admit x.x

also apparently your blog post has quite good SEO so this addition isn't just shouting into the void, will definitely show up for someone
