### ISSUE TITLE
Neovim 0.5 is already stable; How to make warnings etc. appear immediately?

### ISSUE THREAD

**Issue by RichardBenes** [sharksforarms/sharksforarms.github.io#11]
Hello,

thanks for your article! (it saved me from returning to the VSCode)

I've got one question and two suggestions:

1. According to GIFs in your article, errors, warnings, inlay hints etc. appear nearly instantly as you type. In my case however, I have to save the file (`:w`) first, only then they appear/are updated. Is there some extra configuration needed for this to work?
2. As the header says, neovim 0.5.0 is already stable. It's not in Debian's repositories however; there is only either stable 0.4.3 by default, stable 0.4.4 if it's stable PPA is added, or nightly 0.6 if unstable PPA is added. So compiling from source is one the choices to get it
3. As a absolute beginner in Neovim, I would be grateful for a quick mention about where all the configuration should go (I put it all in `~/.config/nvim/init.vim` and it seems OK)

Best regards,
Richard Beneš

**Comment by sharksforarms** [comment]
@RichardBenes thanks for your suggestions!
1. I didn't update the GIFs as time went on... This may be an issue with rust-tools, I'll need to investigate further. I also experience this, but I do `:w` so often that I don't even notice. 
2. Will update
3. That's a good point, I can add a small section. The new way of doing things is with `init.lua`, but waiting on the ecosystem to stabilize a bit before migrating to this.
