### ISSUE TITLE
Possibly add example for 'format on write' to neovim post

### ISSUE THREAD

**Issue by jam1garner** [sharksforarms/sharksforarms.github.io#12]
The following code:

```vim
autocmd BufWritePre *.rs lua vim.lsp.buf.formatting_sync(nil, 200)
```

enables formatting on write for rust files with a 200 millisecond timeout. I think formatting is one of the things to blogpost/config could use, even if it isn't in the form of format-on-write.

An example for a `:Format` command as an alternative:

```vim
:command Format lua vim.lsp.buf.formatting_sync(nil, 3000)
```

with a 3 second timeout.

**Comment by sharksforarms** [comment]
Added a small example to the post
