### ISSUE TITLE
Rename symbol

### ISSUE THREAD

**Issue by waldoplus** [sharksforarms/sharksforarms.github.io#14]
Thank-you for the awesome setup. In VS Code, by pressing F2 on a symbol, you can rename that symbol throughout the document. Is there any way to configure this on neovim?

**Comment by sharksforarms** [comment]
Yep!

Something like: `nnoremap <silent> <F2> <cmd>lua vim.lsp.buf.rename()<CR>`

**Comment by waldoplus** [comment]
Works like a charm! Thanks!
