### ISSUE TITLE
`vim.lsp.diagnostic.show_line_diagnostics()` is deprecated

### ISSUE THREAD

**Issue by thanethomson** [sharksforarms/sharksforarms.github.io#16]
I'm currently using Neovim v0.6.1, and get an error at [this line](https://github.com/sharksforarms/neovim-rust/blob/231a44d289f20405884a0dbf870bd9e7cb8eb68b/neovim-init-lsp.vim#L148) of the config stating that the `show_line_diagnostics()` method is deprecated.

Apparently this has been replaced by `vim.diagnostic.open_float()`. This seems related to https://github.com/neovim/neovim/issues/15154

**Comment by sharksforarms** [comment]
Updated the blog and neovim-rust repo, thanks!
