### ISSUE TITLE
neovim-rust: remove `select = true`. It overrides `noselect`.

### ISSUE THREAD

**Issue by charliemikels** [sharksforarms/sharksforarms.github.io#21]
On the [neovim-rust](https://sharksforarms.dev/posts/neovim-rust/) page, you set up the auto completion plugin with the options:

```vim
set completeopt=menuone,noinsert,noselect
```

but later, you also change the behavior of `enter` in a mappings block

```Lua
    ['<CR>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Insert,
      select = true,
    })
```

The `select = true` part appears to override the `noselect` option. You should consider removing the `select = true` line in order to fix `noselect`. Or you could remove both lines to keep the current functionality the same, while being simple for nvim newcomers who stumble on your guide to add noselect later.

This issue is mostly because I spent like half an hour figuring out why noselect wasn't working, and eventually found my answer in the key mappings.

**Comment by sharksforarms** [comment]
@charliemikels thanks for raising this. I think there's a slight confusion on the behaviours of each option.

What is the behaviour you're looking for?

`noselect` is used to give control to nvim-cmp on selecting an item from the list.
`select = true` is used to select the first element, if none is selected.

**Note: nvim-cmp does select the first item in the menu by default.**

Have you tried `preselect = cmp.PreselectMode.None` ?

For reference: https://github.com/hrsh7th/nvim-cmp/blob/main/doc/cmp.txt

```
*cmp.confirm* (option: cmp.ConfirmOption, callback: function)
  Accepts the currently selected completion item.
  If you didn't select any item and the option table contains `select = true`,
  nvim-cmp will automatically select the first item.
```

```
FAQ                                                                    *cmp-faq*

Why does cmp automatically select a particular item? ~
How to disable the preselect feature? ~

  Nvim-cmp respects the LSP (Language Server Protocol) specification.
  The LSP spec defines the `preselect` feature for completion.

  You can disable the `preselect` feature like this:
>
  cmp.setup {
    preselect = cmp.PreselectMode.None
  }
```

**Comment by charliemikels** [comment]
I might be a bit confused. Here's what I was running into. 

I sometimes program in V, a language that doesn't have semicolons. Sometimes the last word in the line has an unwanted completion suggestions. By default your config prevents me from creating a new line because when a suggestion is available, enter applies the suggestion. In order to create a new line I have to first add a space to exit the word, or move the cursor to start of the next line and add the new line there. 

I wanted to prevent vim from auto entering text when I press enter, requiring me to always press tab to select the item first. From my understanding, this is what the noselect option was supposed to do. (Especially since you've included a comment above noselect that says so.)

I was able to get the behavior I was wanting by removing the "select" line from the CR mapping later in the file. To me it felt like "select = true" and "noselect" we're fighting over the same option, and it might have been a mistake to include both lines of only one is needed. 

But it now sounds like the two lines have subtle differences and you're utilizing them intentionally. So if that's the case, you can probably ignore my issue. But I would suggest modifying the comment by noselect to clarify your config's behavior.

(Also, this is a Rust guide. Rust's language server is way smarter than V's, and semicolons break completion suggestions at the end of a line anyways. So my particular issue is far more infrequent in Rust.)

**Comment by sharksforarms** [comment]
Clarified the statement. Thanks for raising the issue.

Did `cmp.PreselectMode.None` work out for you?

Will close this for now.
