### ISSUE TITLE
How to select code actions

### ISSUE THREAD

**Issue by zbraniecki** [sharksforarms/sharksforarms.github.io#3]
Thank you so much for your guide! I just followed it and my experience of working in Rust is in NeoVim 0.5 is now much better than what I had with VS Code!

The most common feature I miss is ability to populate a trait. I know that rust-analyzer has an `intent` for that, but I don't remember where it is, how it's called or how to implement the binding.

What I'm talking about is that when I have to impl `PartialEq`, `Display` etc. I'd love to be able to just say `impl Display for X` and somehow get the body of that populated with a template.

A shortcut for that would be a lifesaver!

(similarly, intent to populate missing match arms would be great!)

**Comment by sharksforarms** [comment]
Yes! So like this:

```vim
nnoremap <silent> ga    <cmd>lua vim.lsp.buf.code_action()<CR>
```

![Peek 2020-09-29 14-22](https://user-images.githubusercontent.com/10912917/94600180-8915fb80-025f-11eb-948e-50ff578ec458.gif)

**Comment by zbraniecki** [comment]
woa! yes!! Thank you :D

**Comment by zbraniecki** [comment]
You didn't add it to your tutorial. Is there a reason you don't want to?

**Comment by sharksforarms** [comment]
I took what was suggested in `:help lsp` I'll update it soon :)

**Comment by sharksforarms** [comment]
Done!
