### ISSUE TITLE
can you add more plug into it?

### ISSUE THREAD

**Issue by magj2006** [sharksforarms/sharksforarms.github.io#4]
It's very nice manual. thank you.  Most function is ok while I apply configuration as you supplied. but I have two issue: one is that the comment can not be shown.  another is that the color which show diagnostics is white, not red, I already used nord-vim. and can you add other plug into it, like tree explorer, execute cmd without exit current window.

**Comment by sharksforarms** [comment]
Hi @magj2006 are you able to provide your config and screenshots? Also, the version of neovim you're using

**Comment by magj2006** [comment]
@sharksforarms  yes. the version of nvim is NVIM v0.5.0-dev+948-g2debabb08, and terminal is Alacrity and shell is zsh.

<img width="435" alt="屏幕快照 2020-12-22 上午12 07 20" src="https://user-images.githubusercontent.com/8394789/102812940-c797fe00-43e9-11eb-91b6-e93b227faacf.png">

[my config file is here. 
](https://github.com/magj2006/rust-diary/blob/master/init.vim)

**Comment by sharksforarms** [comment]
If I run it in a docker container, mine looks like:
![image](https://user-images.githubusercontent.com/10912917/102832955-c51faf00-43bd-11eb-97db-bcf9466f16d9.png)

**Comment by sharksforarms** [comment]
1. comment cannot be shown -- possibly related to your color setup? Did you try not using nord?
2. diagnostics color; These are controlled with the highlight groups defined in `:help lsp-highlight`, the reason why it might be white vs red now is because of the switch from diagnostic.nvim plugin to built-in diagnostics: https://github.com/sharksforarms/sharksforarms.github.io/commit/eb76e70eb697d913b87c656de6ef959460f4abb2

**Comment by sharksforarms** [comment]
You can also try `set termguicolors` this might change something! Let me know if you figure it out :)

with termguicolors:
![image](https://user-images.githubusercontent.com/10912917/102834009-c2728900-43c0-11eb-830c-ae5fdba3556d.png)

**Comment by magj2006** [comment]
> 1. comment cannot be shown -- possibly related to your color setup? Did you try not using nord?
> 2. diagnostics color; These are controlled with the highlight groups defined in `:help lsp-highlight`, the reason why it might be white vs red now is because of the switch from diagnostic.nvim plugin to built-in diagnostics: [eb76e70](https://github.com/sharksforarms/sharksforarms.github.io/commit/eb76e70eb697d913b87c656de6ef959460f4abb2)

I already try not using nord, but comment isn't shown yet. 

and diagnostics color is working now 👍

**Comment by sharksforarms** [comment]
@magj2006 let me know if you figure it out or if there's anything I can change in the article!

**Comment by magj2006** [comment]
@sharksforarms Thank you so much, It's working now.
