### ISSUE TITLE
Neovim and Rust article - possible completion improvement

### ISSUE THREAD

**Issue by tekul** [sharksforarms/sharksforarms.github.io#5]
Hi. Thanks for the article. I found it really useful in setting things up for Rust dev while switching back to vim/neovim. I noticed that `:help completion` seems to [have been updated](https://github.com/nvim-lua/completion-nvim/commit/5c153f8ae094867a414cb2a7c0f59454299f17b3) since your article so I think you can now write 

```
imap <tab> <Plug>(completion_smart_tab)
```
to enable tab completion.

**Comment by sharksforarms** [comment]
Awesome! Thanks for letting me know. I'll look into updating the article and https://github.com/sharksforarms/vim-rust

**Comment by sharksforarms** [comment]
Awesome! Thanks for letting me know. I'll look into updating the article and https://github.com/sharksforarms/vim-rust

**Comment by sharksforarms** [comment]
Updated post!
