### ISSUE TITLE
Question : Hide Warning/Error virtual text

### ISSUE THREAD

**Issue by kodesoul** [sharksforarms/sharksforarms.github.io#7]
Hello ! I found your blog post very informative, Thank you very much !

I come from using Coc and there is a behaviour I would like to reproduce. Is there a way to hide the warnings/error virtual text and only display them when my cursor is over the problematic code snippet ?

I find the virtual text very distracting.

Hope to hear from you soon. Thanks in advance.

**Comment by sharksforarms** [comment]
Hey @princebett here's something to get you started:

```diff
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
  vim.lsp.diagnostic.on_publish_diagnostics, {
-    virtual_text = true,
+    virtual_text = false,
    signs = true,
    update_in_insert = true,
  }
)
```

Also, for the latest and greatest setup, check out this repo: https://github.com/sharksforarms/vim-rust

Edit: My current config is based around this one: https://github.com/sharksforarms/vim-rust/blob/master/neovim-init-lsp-compe.vim

![Peek 2021-04-25 19-14](https://user-images.githubusercontent.com/10912917/116012753-73509500-a5fa-11eb-89cc-09dc19700c86.gif)

**Comment by kodesoul** [comment]
Thank you very much !!! It's exactly what I wanted. 

Just subscribed to your blog rss. Looking forward to more of your content =).
