### ISSUE TITLE
Auto completion appears for a millisecond

### ISSUE THREAD

**Issue by zibertszn** [sharksforarms/sharksforarms.github.io#8]
https://user-images.githubusercontent.com/72556979/121687889-8ac0e000-cacb-11eb-8007-928f2fc37e5d.mp4

All settings from neovim-init-lsp.vim

**Comment by sharksforarms** [comment]
Hey @AlePon123 did you find why this was happening? Could be useful to others to know what was wrong :)

**Comment by zibertszn** [comment]
> Hey @AlePon123 did you find why this was happening? Could be useful to others to know what was wrong :)

I just reinstalled neovim 💩
