### ISSUE TITLE
Preconfiguration question

### ISSUE THREAD

**Issue by balroggg** [sharksforarms/sharksforarms.github.io#9]
Thanks for a very useful article.

I think this is unnecessary
`Enable syntax highlighting and file type identification, plugin and indenting`
by nvim-defaults
```
2. Defaults                                                 nvim-defaults

  - Syntax highlighting is enabled by default
  - ":filetype plugin indent on" is enabled by default
```

**Comment by sharksforarms** [comment]
This is true. You should make a PR here: https://github.com/sharksforarms/vim-rust 👍

**Comment by sharksforarms** [comment]
Removed from blog post.
